# Numpy Library

In [1]:
import numpy as np

In [5]:
l = [1,2,3,4]
np.array(l)

array([1, 2, 3, 4])

In [6]:
np.mean(l)

2.5

In [7]:
type(np.array(l))

numpy.ndarray

In [9]:
# Creating numpy arrays
# one dimension
my_array = np.array([1,2,3,4,5])
type(my_array)

numpy.ndarray

In [10]:
my_list = [5,8,1,6]
np.array(my_list)

array([5, 8, 1, 6])

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
m = np.array([[2,5,6],[5,4,9],[5,4,9],[5,4,9],[5,2,9]])
m

array([[2, 5, 6],
       [5, 4, 9],
       [5, 4, 9],
       [5, 4, 9],
       [5, 2, 9]])

In [15]:
m.shape

(5, 3)

In [17]:
# Built in Methods
# arange

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.arange(20,0,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [21]:
# Generate arrays of zero and 1

np.ones(3)

array([1., 1., 1.])

In [22]:
np.zeros(4)

array([0., 0., 0., 0.])

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# Linspace

np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [28]:
np.linspace(0,100,101)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

In [29]:
np.linspace(0,10,101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [30]:
# eye or identity matrix
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [3]:
# Random numbers
# Uniform
np.random.rand(5,3)  # It is only in 0 to 1

array([[0.20012434, 0.8740245 , 0.47543397],
       [0.7811097 , 0.30627056, 0.11806638],
       [0.66827936, 0.03850312, 0.97184158],
       [0.49326695, 0.64421615, 0.37033626],
       [0.09117085, 0.31561416, 0.10653297]])

In [32]:
# If want normal then

np.random.randn(5,3)

array([[-0.41026227, -0.16445468, -1.13180772],
       [ 0.81171253, -0.54396461,  0.59900325],
       [-0.98934337, -0.44655551, -0.283372  ],
       [ 2.20164904,  0.95226882, -0.25818195],
       [ 0.18687337,  2.15813297, -0.58245372]])

In [34]:
# Integer no
# Here we want to define range

np.random.randint(0,50,10)


array([ 6,  8, 42, 18, 27, 23, 42, 26, 14, 27])

In [39]:
# Reshape
arr = np.arange(18)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [40]:
arr.shape

(18,)

In [41]:
arr.reshape(6,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [44]:
# Matrix Aggregation

arr = np.random.randint(1,50,20)
arr

array([36, 10, 45, 27, 43, 34, 43,  5,  1,  6, 43, 34, 21, 16, 23, 22, 27,
       17, 33, 40])

In [45]:
arr.max()

45

In [46]:
arr.argmax()  # Max no position

2

In [47]:
arr.min()

1

In [48]:
arr.argmin() # Min no position

8

In [52]:
# Diamension

a = np.random.rand(2,1,2)
print(a)
print("diamension:", a.ndim)

[[[0.02743814 0.15138176]]

 [[0.18702872 0.86038152]]]
diamension: 3


In [53]:
# Arithmetic operations

l = np.array([1,2,3])
l1 = np.array([5,6,7])
l+l1

array([ 6,  8, 10])

In [54]:
l-l1

array([-4, -4, -4])

In [55]:
l*l1

array([ 5, 12, 21])

In [56]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
arr**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [58]:
arr*3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [59]:
# Dot product

a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [60]:
b = np.array([[11,12],[13,14]])
b

array([[11, 12],
       [13, 14]])

In [61]:
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [4]:
# Universal array functions

dp = np.array([[4,9,16],[25,36,56]])
dp

array([[ 4,  9, 16],
       [25, 36, 56]])

In [5]:
np.sqrt(dp)

array([[2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.48331477]])

In [6]:
np.exp(dp)

array([[5.45981500e+01, 8.10308393e+03, 8.88611052e+06],
       [7.20048993e+10, 4.31123155e+15, 2.09165950e+24]])

In [7]:
np.log(dp)

array([[1.38629436, 2.19722458, 2.77258872],
       [3.21887582, 3.58351894, 4.02535169]])

In [8]:
np.sin(dp)

array([[-0.7568025 ,  0.41211849, -0.28790332],
       [-0.13235175, -0.99177885, -0.521551  ]])

In [9]:
# around function

np.around(2.15658,3)

2.157

In [13]:
x = np.random.randint(50,100,10)

print(x)

[95 91 82 76 65 91 70 61 77 95]


In [14]:
x = np.random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[5 7 9 9 9]
 [9 7 3 9 9]
 [3 5 5 5 9]]


In [16]:
x = np.random.choice([3, 5, 7, 9])

print(x)

3
